apiVersion: v1
kind: Secret
metadata:
  name: kadamtekton
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
    username: <your-dockerhub-username>
    password: <your-dockerhub-password>
